CREATE TABLE "FLIGHT" (
  "ID" INT(10) NOT NULL AUTO_INCREMENT,
  "STARTING_ENDPOINT_NAME" VARCHAR(100) NOT NULL,
  "ENDING_ENDPOINT_NAME" VARCHAR(100) NOT NULL,
  "DISTANCE" INT(10),
  "COST" DOUBLE,
  "START_DATE" TIMESTAMP,
  "AVAILABLE_TICKET_COUNT" INT(10),
  "FULL_TICKET_COUNT" INT(10),  
  PRIMARY KEY ("ID")
) DEFAULT CHARSET=utf8;

CREATE TABLE "USER" (
  "ID" INT(10) NOT NULL AUTO_INCREMENT,
  "FIRST_NAME" VARCHAR(100) NOT NULL,
  "LAST_NAME" VARCHAR(100) NOT NULL,
  "LOGIN" VARCHAR(100) NOT NULL UNIQUE,
  "PASSWORD" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("ID"),
) DEFAULT CHARSET=utf8;

CREATE TABLE "REVIEW" (
  "ID" INT(10) NOT NULL AUTO_INCREMENT,
  "FLIGHT_ID" INT(10) NOT NULL,
  "USER_ID" INT(10) NOT NULL,
  "POST_DATE" TIMESTAMP,
  "HEADER" VARCHAR(100) NOT NULL,
  "REVIEW" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("ID"),
  FOREIGN KEY ("FLIGHT_ID") REFERENCES "FLIGHT"("ID"),
  FOREIGN KEY ("USER_ID") REFERENCES"USER"("ID"),
) DEFAULT CHARSET=utf8;

CREATE TABLE "TICKET" (
  "ID" INT(10) NOT NULL AUTO_INCREMENT,
  "PLACE_NUMBER" INT(10) NOT NULL,
  "FLIGHT_ID" INT(10) NOT NULL,
  "USER_ID" INT(10) NOT NULL,
  FOREIGN KEY ("FLIGHT_ID") REFERENCES "FLIGHT"("ID"),
  FOREIGN KEY ("USER_ID") REFERENCES"USER"("ID"),
  PRIMARY KEY ("ID"),
) DEFAULT CHARSET=utf8;



